name: Code formatting

# Controls when the workflow will run
on: workflow_call

jobs:
  ruff:
    name: Format Python with Ruff
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # https://github.com/astral-sh/ruff-action
      - name: Install Ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          version: "latest"
          args: "--version"
      # Linting and formatting via Ruff
      - name: Run Ruff
        run: |
          ruff check
          ruff format --check
