name: CI

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release*

jobs:
  install:
    name: Testing the installer
    uses: ./.github/workflows/install.yml
    with:
      PY_VERSION: "3.11"
  pytest:
    name: Running the tests
    uses: ./.github/workflows/test.yml
    with:
      PY_VERSION: "3.11"
  format:
   name: Running the Python formatter
   uses: ./.github/workflows/format.yml

